# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='emulation',
  syntax='proto3',
  serialized_pb=_b('\n\trpc.proto\x12\temulation\"R\n\x12SendPaymentRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x03\"\x15\n\x13SendPaymentResponse\"=\n\x12OpenChannelRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0elocked_by_user\x18\x02 \x01(\x03\")\n\x13OpenChannelResponse\x12\x12\n\nchannel_id\x18\x03 \x01(\t\")\n\x13\x43loseChannelRequest\x12\x12\n\nchannel_id\x18\x03 \x01(\t\"\x16\n\x14\x43loseChannelResponse\".\n\x1aSetBlockGenDurationRequest\x12\x10\n\x08\x64uration\x18\x03 \x01(\x03\"\x1d\n\x1bSetBlockGenDurationResponse\"&\n\x17SetBlockchainFeeRequest\x12\x0b\n\x03\x66\x65\x65\x18\x03 \x01(\x03\"\x1a\n\x18SetBlockchainFeeResponse\"=\n\x17SetUserConnectedRequest\x12\x11\n\tis_online\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"\x1a\n\x18SetUserConnectedResponse2\x97\x04\n\x08\x45mulator\x12L\n\x0bSendPayment\x12\x1d.emulation.SendPaymentRequest\x1a\x1e.emulation.SendPaymentResponse\x12L\n\x0bOpenChannel\x12\x1d.emulation.OpenChannelRequest\x1a\x1e.emulation.OpenChannelResponse\x12O\n\x0c\x43loseChannel\x12\x1e.emulation.CloseChannelRequest\x1a\x1f.emulation.CloseChannelResponse\x12[\n\x10SetUserConnected\x12\".emulation.SetUserConnectedRequest\x1a#.emulation.SetUserConnectedResponse\x12\x64\n\x13SetBlockGenDuration\x12%.emulation.SetBlockGenDurationRequest\x1a&.emulation.SetBlockGenDurationResponse\x12[\n\x10SetBlockchainFee\x12\".emulation.SetBlockchainFeeRequest\x1a#.emulation.SetBlockchainFeeResponseb\x06proto3')
)




_SENDPAYMENTREQUEST = _descriptor.Descriptor(
  name='SendPaymentRequest',
  full_name='emulation.SendPaymentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='emulation.SendPaymentRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='emulation.SendPaymentRequest.sender', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='emulation.SendPaymentRequest.receiver', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='emulation.SendPaymentRequest.amount', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=106,
)


_SENDPAYMENTRESPONSE = _descriptor.Descriptor(
  name='SendPaymentResponse',
  full_name='emulation.SendPaymentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=129,
)


_OPENCHANNELREQUEST = _descriptor.Descriptor(
  name='OpenChannelRequest',
  full_name='emulation.OpenChannelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='emulation.OpenChannelRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locked_by_user', full_name='emulation.OpenChannelRequest.locked_by_user', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=192,
)


_OPENCHANNELRESPONSE = _descriptor.Descriptor(
  name='OpenChannelResponse',
  full_name='emulation.OpenChannelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='emulation.OpenChannelResponse.channel_id', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=235,
)


_CLOSECHANNELREQUEST = _descriptor.Descriptor(
  name='CloseChannelRequest',
  full_name='emulation.CloseChannelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='emulation.CloseChannelRequest.channel_id', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=278,
)


_CLOSECHANNELRESPONSE = _descriptor.Descriptor(
  name='CloseChannelResponse',
  full_name='emulation.CloseChannelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=302,
)


_SETBLOCKGENDURATIONREQUEST = _descriptor.Descriptor(
  name='SetBlockGenDurationRequest',
  full_name='emulation.SetBlockGenDurationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='emulation.SetBlockGenDurationRequest.duration', index=0,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=350,
)


_SETBLOCKGENDURATIONRESPONSE = _descriptor.Descriptor(
  name='SetBlockGenDurationResponse',
  full_name='emulation.SetBlockGenDurationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=381,
)


_SETBLOCKCHAINFEEREQUEST = _descriptor.Descriptor(
  name='SetBlockchainFeeRequest',
  full_name='emulation.SetBlockchainFeeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fee', full_name='emulation.SetBlockchainFeeRequest.fee', index=0,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=421,
)


_SETBLOCKCHAINFEERESPONSE = _descriptor.Descriptor(
  name='SetBlockchainFeeResponse',
  full_name='emulation.SetBlockchainFeeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=449,
)


_SETUSERCONNECTEDREQUEST = _descriptor.Descriptor(
  name='SetUserConnectedRequest',
  full_name='emulation.SetUserConnectedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_online', full_name='emulation.SetUserConnectedRequest.is_online', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='emulation.SetUserConnectedRequest.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=512,
)


_SETUSERCONNECTEDRESPONSE = _descriptor.Descriptor(
  name='SetUserConnectedResponse',
  full_name='emulation.SetUserConnectedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=540,
)

DESCRIPTOR.message_types_by_name['SendPaymentRequest'] = _SENDPAYMENTREQUEST
DESCRIPTOR.message_types_by_name['SendPaymentResponse'] = _SENDPAYMENTRESPONSE
DESCRIPTOR.message_types_by_name['OpenChannelRequest'] = _OPENCHANNELREQUEST
DESCRIPTOR.message_types_by_name['OpenChannelResponse'] = _OPENCHANNELRESPONSE
DESCRIPTOR.message_types_by_name['CloseChannelRequest'] = _CLOSECHANNELREQUEST
DESCRIPTOR.message_types_by_name['CloseChannelResponse'] = _CLOSECHANNELRESPONSE
DESCRIPTOR.message_types_by_name['SetBlockGenDurationRequest'] = _SETBLOCKGENDURATIONREQUEST
DESCRIPTOR.message_types_by_name['SetBlockGenDurationResponse'] = _SETBLOCKGENDURATIONRESPONSE
DESCRIPTOR.message_types_by_name['SetBlockchainFeeRequest'] = _SETBLOCKCHAINFEEREQUEST
DESCRIPTOR.message_types_by_name['SetBlockchainFeeResponse'] = _SETBLOCKCHAINFEERESPONSE
DESCRIPTOR.message_types_by_name['SetUserConnectedRequest'] = _SETUSERCONNECTEDREQUEST
DESCRIPTOR.message_types_by_name['SetUserConnectedResponse'] = _SETUSERCONNECTEDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendPaymentRequest = _reflection.GeneratedProtocolMessageType('SendPaymentRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENDPAYMENTREQUEST,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:emulation.SendPaymentRequest)
  ))
_sym_db.RegisterMessage(SendPaymentRequest)

SendPaymentResponse = _reflection.GeneratedProtocolMessageType('SendPaymentResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDPAYMENTRESPONSE,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:emulation.SendPaymentResponse)
  ))
_sym_db.RegisterMessage(SendPaymentResponse)

OpenChannelRequest = _reflection.GeneratedProtocolMessageType('OpenChannelRequest', (_message.Message,), dict(
  DESCRIPTOR = _OPENCHANNELREQUEST,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:emulation.OpenChannelRequest)
  ))
_sym_db.RegisterMessage(OpenChannelRequest)

OpenChannelResponse = _reflection.GeneratedProtocolMessageType('OpenChannelResponse', (_message.Message,), dict(
  DESCRIPTOR = _OPENCHANNELRESPONSE,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:emulation.OpenChannelResponse)
  ))
_sym_db.RegisterMessage(OpenChannelResponse)

CloseChannelRequest = _reflection.GeneratedProtocolMessageType('CloseChannelRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLOSECHANNELREQUEST,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:emulation.CloseChannelRequest)
  ))
_sym_db.RegisterMessage(CloseChannelRequest)

CloseChannelResponse = _reflection.GeneratedProtocolMessageType('CloseChannelResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLOSECHANNELRESPONSE,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:emulation.CloseChannelResponse)
  ))
_sym_db.RegisterMessage(CloseChannelResponse)

SetBlockGenDurationRequest = _reflection.GeneratedProtocolMessageType('SetBlockGenDurationRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETBLOCKGENDURATIONREQUEST,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:emulation.SetBlockGenDurationRequest)
  ))
_sym_db.RegisterMessage(SetBlockGenDurationRequest)

SetBlockGenDurationResponse = _reflection.GeneratedProtocolMessageType('SetBlockGenDurationResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETBLOCKGENDURATIONRESPONSE,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:emulation.SetBlockGenDurationResponse)
  ))
_sym_db.RegisterMessage(SetBlockGenDurationResponse)

SetBlockchainFeeRequest = _reflection.GeneratedProtocolMessageType('SetBlockchainFeeRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETBLOCKCHAINFEEREQUEST,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:emulation.SetBlockchainFeeRequest)
  ))
_sym_db.RegisterMessage(SetBlockchainFeeRequest)

SetBlockchainFeeResponse = _reflection.GeneratedProtocolMessageType('SetBlockchainFeeResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETBLOCKCHAINFEERESPONSE,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:emulation.SetBlockchainFeeResponse)
  ))
_sym_db.RegisterMessage(SetBlockchainFeeResponse)

SetUserConnectedRequest = _reflection.GeneratedProtocolMessageType('SetUserConnectedRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETUSERCONNECTEDREQUEST,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:emulation.SetUserConnectedRequest)
  ))
_sym_db.RegisterMessage(SetUserConnectedRequest)

SetUserConnectedResponse = _reflection.GeneratedProtocolMessageType('SetUserConnectedResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETUSERCONNECTEDRESPONSE,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:emulation.SetUserConnectedResponse)
  ))
_sym_db.RegisterMessage(SetUserConnectedResponse)



_EMULATOR = _descriptor.ServiceDescriptor(
  name='Emulator',
  full_name='emulation.Emulator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=543,
  serialized_end=1078,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendPayment',
    full_name='emulation.Emulator.SendPayment',
    index=0,
    containing_service=None,
    input_type=_SENDPAYMENTREQUEST,
    output_type=_SENDPAYMENTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OpenChannel',
    full_name='emulation.Emulator.OpenChannel',
    index=1,
    containing_service=None,
    input_type=_OPENCHANNELREQUEST,
    output_type=_OPENCHANNELRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CloseChannel',
    full_name='emulation.Emulator.CloseChannel',
    index=2,
    containing_service=None,
    input_type=_CLOSECHANNELREQUEST,
    output_type=_CLOSECHANNELRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetUserConnected',
    full_name='emulation.Emulator.SetUserConnected',
    index=3,
    containing_service=None,
    input_type=_SETUSERCONNECTEDREQUEST,
    output_type=_SETUSERCONNECTEDRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetBlockGenDuration',
    full_name='emulation.Emulator.SetBlockGenDuration',
    index=4,
    containing_service=None,
    input_type=_SETBLOCKGENDURATIONREQUEST,
    output_type=_SETBLOCKGENDURATIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetBlockchainFee',
    full_name='emulation.Emulator.SetBlockchainFee',
    index=5,
    containing_service=None,
    input_type=_SETBLOCKCHAINFEEREQUEST,
    output_type=_SETBLOCKCHAINFEERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMULATOR)

DESCRIPTOR.services_by_name['Emulator'] = _EMULATOR

# @@protoc_insertion_point(module_scope)
