# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statrpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='statrpc.proto',
  package='statrpc',
  syntax='proto3',
  serialized_pb=_b('\n\rstatrpc.proto\x12\x07statrpc\"\x16\n\x14GetStatParamsRequest\"\xe8\x01\n\x15GetStatParamsResponse\x12\x0e\n\x06profit\x18\x02 \x01(\x03\x12\x10\n\x08gain_sum\x18\x03 \x01(\x01\x12\x16\n\x0elocked_balance\x18\x04 \x01(\x03\x12\x0f\n\x07ROI_day\x18\x05 \x01(\x01\x12\x14\n\x0c\x66ree_balance\x18\x06 \x01(\x03\x12\x11\n\tprofit_av\x18\x07 \x01(\x01\x12\x13\n\x0bgain_sum_av\x18\x08 \x01(\x01\x12\x19\n\x11locked_balance_av\x18\t \x01(\x01\x12\x12\n\nROI_day_av\x18\n \x01(\x01\x12\x17\n\x0f\x66ree_balance_av\x18\x0b \x01(\x01\x32_\n\rGetStatistics\x12N\n\rGetStatParams\x12\x1d.statrpc.GetStatParamsRequest\x1a\x1e.statrpc.GetStatParamsResponseb\x06proto3')
)




_GETSTATPARAMSREQUEST = _descriptor.Descriptor(
  name='GetStatParamsRequest',
  full_name='statrpc.GetStatParamsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=48,
)


_GETSTATPARAMSRESPONSE = _descriptor.Descriptor(
  name='GetStatParamsResponse',
  full_name='statrpc.GetStatParamsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profit', full_name='statrpc.GetStatParamsResponse.profit', index=0,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gain_sum', full_name='statrpc.GetStatParamsResponse.gain_sum', index=1,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locked_balance', full_name='statrpc.GetStatParamsResponse.locked_balance', index=2,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ROI_day', full_name='statrpc.GetStatParamsResponse.ROI_day', index=3,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='free_balance', full_name='statrpc.GetStatParamsResponse.free_balance', index=4,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profit_av', full_name='statrpc.GetStatParamsResponse.profit_av', index=5,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gain_sum_av', full_name='statrpc.GetStatParamsResponse.gain_sum_av', index=6,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locked_balance_av', full_name='statrpc.GetStatParamsResponse.locked_balance_av', index=7,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ROI_day_av', full_name='statrpc.GetStatParamsResponse.ROI_day_av', index=8,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='free_balance_av', full_name='statrpc.GetStatParamsResponse.free_balance_av', index=9,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=283,
)

DESCRIPTOR.message_types_by_name['GetStatParamsRequest'] = _GETSTATPARAMSREQUEST
DESCRIPTOR.message_types_by_name['GetStatParamsResponse'] = _GETSTATPARAMSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetStatParamsRequest = _reflection.GeneratedProtocolMessageType('GetStatParamsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSTATPARAMSREQUEST,
  __module__ = 'statrpc_pb2'
  # @@protoc_insertion_point(class_scope:statrpc.GetStatParamsRequest)
  ))
_sym_db.RegisterMessage(GetStatParamsRequest)

GetStatParamsResponse = _reflection.GeneratedProtocolMessageType('GetStatParamsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETSTATPARAMSRESPONSE,
  __module__ = 'statrpc_pb2'
  # @@protoc_insertion_point(class_scope:statrpc.GetStatParamsResponse)
  ))
_sym_db.RegisterMessage(GetStatParamsResponse)



_GETSTATISTICS = _descriptor.ServiceDescriptor(
  name='GetStatistics',
  full_name='statrpc.GetStatistics',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=285,
  serialized_end=380,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStatParams',
    full_name='statrpc.GetStatistics.GetStatParams',
    index=0,
    containing_service=None,
    input_type=_GETSTATPARAMSREQUEST,
    output_type=_GETSTATPARAMSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETSTATISTICS)

DESCRIPTOR.services_by_name['GetStatistics'] = _GETSTATISTICS

# @@protoc_insertion_point(module_scope)
