# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hubrpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hubrpc.proto',
  package='hubrpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0chubrpc.proto\x12\x06hubrpc\"B\n\x0fSetStateRequest\x12\x0c\n\x04time\x18\x01 \x01(\x04\x12!\n\x08\x63hannels\x18\x02 \x03(\x0b\x32\x0f.hubrpc.Channel\"\x12\n\x10SetStateResponse\"F\n\x07\x43hannel\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x12\n\nchannel_id\x18\x02 \x01(\x04\x12\x16\n\x0erouter_balance\x18\x03 \x01(\x04\x32H\n\x07Manager\x12=\n\x08SetState\x12\x17.hubrpc.SetStateRequest\x1a\x18.hubrpc.SetStateResponseb\x06proto3')
)




_SETSTATEREQUEST = _descriptor.Descriptor(
  name='SetStateRequest',
  full_name='hubrpc.SetStateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='hubrpc.SetStateRequest.time', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channels', full_name='hubrpc.SetStateRequest.channels', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=90,
)


_SETSTATERESPONSE = _descriptor.Descriptor(
  name='SetStateResponse',
  full_name='hubrpc.SetStateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=110,
)


_CHANNEL = _descriptor.Descriptor(
  name='Channel',
  full_name='hubrpc.Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='hubrpc.Channel.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='hubrpc.Channel.channel_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='router_balance', full_name='hubrpc.Channel.router_balance', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=182,
)

_SETSTATEREQUEST.fields_by_name['channels'].message_type = _CHANNEL
DESCRIPTOR.message_types_by_name['SetStateRequest'] = _SETSTATEREQUEST
DESCRIPTOR.message_types_by_name['SetStateResponse'] = _SETSTATERESPONSE
DESCRIPTOR.message_types_by_name['Channel'] = _CHANNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetStateRequest = _reflection.GeneratedProtocolMessageType('SetStateRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETSTATEREQUEST,
  __module__ = 'hubrpc_pb2'
  # @@protoc_insertion_point(class_scope:hubrpc.SetStateRequest)
  ))
_sym_db.RegisterMessage(SetStateRequest)

SetStateResponse = _reflection.GeneratedProtocolMessageType('SetStateResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETSTATERESPONSE,
  __module__ = 'hubrpc_pb2'
  # @@protoc_insertion_point(class_scope:hubrpc.SetStateResponse)
  ))
_sym_db.RegisterMessage(SetStateResponse)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), dict(
  DESCRIPTOR = _CHANNEL,
  __module__ = 'hubrpc_pb2'
  # @@protoc_insertion_point(class_scope:hubrpc.Channel)
  ))
_sym_db.RegisterMessage(Channel)



_MANAGER = _descriptor.ServiceDescriptor(
  name='Manager',
  full_name='hubrpc.Manager',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=184,
  serialized_end=256,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetState',
    full_name='hubrpc.Manager.SetState',
    index=0,
    containing_service=None,
    input_type=_SETSTATEREQUEST,
    output_type=_SETSTATERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MANAGER)

DESCRIPTOR.services_by_name['Manager'] = _MANAGER

# @@protoc_insertion_point(module_scope)
