// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package emulation is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	SendPaymentRequest
	SendPaymentResponse
	OpenChannelRequest
	OpenChannelResponse
	CloseChannelRequest
	CloseChannelResponse
	SetBlockGenDurationRequest
	SetBlockGenDurationResponse
	SetBlockchainFeeRequest
	SetBlockchainFeeResponse
	SetUserActiveRequest
	SetUserActiveResponse
*/
package emulation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SendPaymentRequest struct {
	// Sender is the id of user which sends the payment. If equals zero than we
	// believe that router is the sender.
	Sender string `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	// Receiver is the id of user who receive the payment. If equals zero than we
	// believe that router is the receiver.
	Receiver string `protobuf:"bytes,2,opt,name=receiver" json:"receiver,omitempty"`
	Amount   int64  `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
}

func (m *SendPaymentRequest) Reset()                    { *m = SendPaymentRequest{} }
func (m *SendPaymentRequest) String() string            { return proto.CompactTextString(m) }
func (*SendPaymentRequest) ProtoMessage()               {}
func (*SendPaymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SendPaymentRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *SendPaymentRequest) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *SendPaymentRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type SendPaymentResponse struct {
}

func (m *SendPaymentResponse) Reset()                    { *m = SendPaymentResponse{} }
func (m *SendPaymentResponse) String() string            { return proto.CompactTextString(m) }
func (*SendPaymentResponse) ProtoMessage()               {}
func (*SendPaymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type OpenChannelRequest struct {
	UserId       string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	LockedByUser int64  `protobuf:"varint,2,opt,name=locked_by_user,json=lockedByUser" json:"locked_by_user,omitempty"`
}

func (m *OpenChannelRequest) Reset()                    { *m = OpenChannelRequest{} }
func (m *OpenChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenChannelRequest) ProtoMessage()               {}
func (*OpenChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OpenChannelRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OpenChannelRequest) GetLockedByUser() int64 {
	if m != nil {
		return m.LockedByUser
	}
	return 0
}

type OpenChannelResponse struct {
	ChannelId string `protobuf:"bytes,3,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
}

func (m *OpenChannelResponse) Reset()                    { *m = OpenChannelResponse{} }
func (m *OpenChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*OpenChannelResponse) ProtoMessage()               {}
func (*OpenChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OpenChannelResponse) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type CloseChannelRequest struct {
	ChannelId string `protobuf:"bytes,3,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
}

func (m *CloseChannelRequest) Reset()                    { *m = CloseChannelRequest{} }
func (m *CloseChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*CloseChannelRequest) ProtoMessage()               {}
func (*CloseChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CloseChannelRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type CloseChannelResponse struct {
}

func (m *CloseChannelResponse) Reset()                    { *m = CloseChannelResponse{} }
func (m *CloseChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*CloseChannelResponse) ProtoMessage()               {}
func (*CloseChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SetBlockGenDurationRequest struct {
	// Duration is the number of millisecond channel has to be in the locked
	// state after it openes or updates.
	Duration int64 `protobuf:"varint,3,opt,name=duration" json:"duration,omitempty"`
}

func (m *SetBlockGenDurationRequest) Reset()                    { *m = SetBlockGenDurationRequest{} }
func (m *SetBlockGenDurationRequest) String() string            { return proto.CompactTextString(m) }
func (*SetBlockGenDurationRequest) ProtoMessage()               {}
func (*SetBlockGenDurationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SetBlockGenDurationRequest) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type SetBlockGenDurationResponse struct {
}

func (m *SetBlockGenDurationResponse) Reset()                    { *m = SetBlockGenDurationResponse{} }
func (m *SetBlockGenDurationResponse) String() string            { return proto.CompactTextString(m) }
func (*SetBlockGenDurationResponse) ProtoMessage()               {}
func (*SetBlockGenDurationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type SetBlockchainFeeRequest struct {
	// fee is the number expressed in satoshis, which blockchain takes for
	// making an computation, transaction creation, i.e. channel updates.
	// TODO(andrew.shvv) Make it real world friendly - calculate fee
	// depending on tx size and fee per kilobyte.
	Fee int64 `protobuf:"varint,3,opt,name=fee" json:"fee,omitempty"`
}

func (m *SetBlockchainFeeRequest) Reset()                    { *m = SetBlockchainFeeRequest{} }
func (m *SetBlockchainFeeRequest) String() string            { return proto.CompactTextString(m) }
func (*SetBlockchainFeeRequest) ProtoMessage()               {}
func (*SetBlockchainFeeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SetBlockchainFeeRequest) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

type SetBlockchainFeeResponse struct {
}

func (m *SetBlockchainFeeResponse) Reset()                    { *m = SetBlockchainFeeResponse{} }
func (m *SetBlockchainFeeResponse) String() string            { return proto.CompactTextString(m) }
func (*SetBlockchainFeeResponse) ProtoMessage()               {}
func (*SetBlockchainFeeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SetUserActiveRequest struct {
	IsOnline bool   `protobuf:"varint,1,opt,name=is_online,json=isOnline" json:"is_online,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *SetUserActiveRequest) Reset()                    { *m = SetUserActiveRequest{} }
func (m *SetUserActiveRequest) String() string            { return proto.CompactTextString(m) }
func (*SetUserActiveRequest) ProtoMessage()               {}
func (*SetUserActiveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SetUserActiveRequest) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

func (m *SetUserActiveRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SetUserActiveResponse struct {
}

func (m *SetUserActiveResponse) Reset()                    { *m = SetUserActiveResponse{} }
func (m *SetUserActiveResponse) String() string            { return proto.CompactTextString(m) }
func (*SetUserActiveResponse) ProtoMessage()               {}
func (*SetUserActiveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*SendPaymentRequest)(nil), "emulation.SendPaymentRequest")
	proto.RegisterType((*SendPaymentResponse)(nil), "emulation.SendPaymentResponse")
	proto.RegisterType((*OpenChannelRequest)(nil), "emulation.OpenChannelRequest")
	proto.RegisterType((*OpenChannelResponse)(nil), "emulation.OpenChannelResponse")
	proto.RegisterType((*CloseChannelRequest)(nil), "emulation.CloseChannelRequest")
	proto.RegisterType((*CloseChannelResponse)(nil), "emulation.CloseChannelResponse")
	proto.RegisterType((*SetBlockGenDurationRequest)(nil), "emulation.SetBlockGenDurationRequest")
	proto.RegisterType((*SetBlockGenDurationResponse)(nil), "emulation.SetBlockGenDurationResponse")
	proto.RegisterType((*SetBlockchainFeeRequest)(nil), "emulation.SetBlockchainFeeRequest")
	proto.RegisterType((*SetBlockchainFeeResponse)(nil), "emulation.SetBlockchainFeeResponse")
	proto.RegisterType((*SetUserActiveRequest)(nil), "emulation.SetUserActiveRequest")
	proto.RegisterType((*SetUserActiveResponse)(nil), "emulation.SetUserActiveResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Emulator service

type EmulatorClient interface {
	//
	// SendPayment is used to emulate the activity of one user sending payment
	// to another within the local router network.
	SendPayment(ctx context.Context, in *SendPaymentRequest, opts ...grpc.CallOption) (*SendPaymentResponse, error)
	//
	// OpenChannel is used to emulate that user has opened the channel with the
	// router.
	OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelResponse, error)
	//
	// CloseChannel is used to emulate that user has closed the channel with the
	// router.
	CloseChannel(ctx context.Context, in *CloseChannelRequest, opts ...grpc.CallOption) (*CloseChannelResponse, error)
	//
	// SetUserActive set user being offline or online, which means that all his
	// openned channels either could or could't be used for receiving and
	// sending payments.
	SetUserActive(ctx context.Context, in *SetUserActiveRequest, opts ...grpc.CallOption) (*SetUserActiveResponse, error)
	//
	// SetBlockGenDuration is used to set the time which is needed for blokc
	// to be generatedtime. This would impact channel creation, channel
	// update and channel close.
	SetBlockGenDuration(ctx context.Context, in *SetBlockGenDurationRequest, opts ...grpc.CallOption) (*SetBlockGenDurationResponse, error)
	//
	// SetBlockchainFee is used to set the fee which blockchain takes for
	// making an computation, transaction creation, i.e. channel updates.
	SetBlockchainFee(ctx context.Context, in *SetBlockchainFeeRequest, opts ...grpc.CallOption) (*SetBlockchainFeeResponse, error)
}

type emulatorClient struct {
	cc *grpc.ClientConn
}

func NewEmulatorClient(cc *grpc.ClientConn) EmulatorClient {
	return &emulatorClient{cc}
}

func (c *emulatorClient) SendPayment(ctx context.Context, in *SendPaymentRequest, opts ...grpc.CallOption) (*SendPaymentResponse, error) {
	out := new(SendPaymentResponse)
	err := grpc.Invoke(ctx, "/emulation.Emulator/SendPayment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorClient) OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelResponse, error) {
	out := new(OpenChannelResponse)
	err := grpc.Invoke(ctx, "/emulation.Emulator/OpenChannel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorClient) CloseChannel(ctx context.Context, in *CloseChannelRequest, opts ...grpc.CallOption) (*CloseChannelResponse, error) {
	out := new(CloseChannelResponse)
	err := grpc.Invoke(ctx, "/emulation.Emulator/CloseChannel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorClient) SetUserActive(ctx context.Context, in *SetUserActiveRequest, opts ...grpc.CallOption) (*SetUserActiveResponse, error) {
	out := new(SetUserActiveResponse)
	err := grpc.Invoke(ctx, "/emulation.Emulator/SetUserActive", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorClient) SetBlockGenDuration(ctx context.Context, in *SetBlockGenDurationRequest, opts ...grpc.CallOption) (*SetBlockGenDurationResponse, error) {
	out := new(SetBlockGenDurationResponse)
	err := grpc.Invoke(ctx, "/emulation.Emulator/SetBlockGenDuration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorClient) SetBlockchainFee(ctx context.Context, in *SetBlockchainFeeRequest, opts ...grpc.CallOption) (*SetBlockchainFeeResponse, error) {
	out := new(SetBlockchainFeeResponse)
	err := grpc.Invoke(ctx, "/emulation.Emulator/SetBlockchainFee", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Emulator service

type EmulatorServer interface {
	//
	// SendPayment is used to emulate the activity of one user sending payment
	// to another within the local router network.
	SendPayment(context.Context, *SendPaymentRequest) (*SendPaymentResponse, error)
	//
	// OpenChannel is used to emulate that user has opened the channel with the
	// router.
	OpenChannel(context.Context, *OpenChannelRequest) (*OpenChannelResponse, error)
	//
	// CloseChannel is used to emulate that user has closed the channel with the
	// router.
	CloseChannel(context.Context, *CloseChannelRequest) (*CloseChannelResponse, error)
	//
	// SetUserActive set user being offline or online, which means that all his
	// openned channels either could or could't be used for receiving and
	// sending payments.
	SetUserActive(context.Context, *SetUserActiveRequest) (*SetUserActiveResponse, error)
	//
	// SetBlockGenDuration is used to set the time which is needed for blokc
	// to be generatedtime. This would impact channel creation, channel
	// update and channel close.
	SetBlockGenDuration(context.Context, *SetBlockGenDurationRequest) (*SetBlockGenDurationResponse, error)
	//
	// SetBlockchainFee is used to set the fee which blockchain takes for
	// making an computation, transaction creation, i.e. channel updates.
	SetBlockchainFee(context.Context, *SetBlockchainFeeRequest) (*SetBlockchainFeeResponse, error)
}

func RegisterEmulatorServer(s *grpc.Server, srv EmulatorServer) {
	s.RegisterService(&_Emulator_serviceDesc, srv)
}

func _Emulator_SendPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorServer).SendPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emulation.Emulator/SendPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorServer).SendPayment(ctx, req.(*SendPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Emulator_OpenChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorServer).OpenChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emulation.Emulator/OpenChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorServer).OpenChannel(ctx, req.(*OpenChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Emulator_CloseChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorServer).CloseChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emulation.Emulator/CloseChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorServer).CloseChannel(ctx, req.(*CloseChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Emulator_SetUserActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorServer).SetUserActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emulation.Emulator/SetUserActive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorServer).SetUserActive(ctx, req.(*SetUserActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Emulator_SetBlockGenDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBlockGenDurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorServer).SetBlockGenDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emulation.Emulator/SetBlockGenDuration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorServer).SetBlockGenDuration(ctx, req.(*SetBlockGenDurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Emulator_SetBlockchainFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBlockchainFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorServer).SetBlockchainFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emulation.Emulator/SetBlockchainFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorServer).SetBlockchainFee(ctx, req.(*SetBlockchainFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Emulator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "emulation.Emulator",
	HandlerType: (*EmulatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPayment",
			Handler:    _Emulator_SendPayment_Handler,
		},
		{
			MethodName: "OpenChannel",
			Handler:    _Emulator_OpenChannel_Handler,
		},
		{
			MethodName: "CloseChannel",
			Handler:    _Emulator_CloseChannel_Handler,
		},
		{
			MethodName: "SetUserActive",
			Handler:    _Emulator_SetUserActive_Handler,
		},
		{
			MethodName: "SetBlockGenDuration",
			Handler:    _Emulator_SetBlockGenDuration_Handler,
		},
		{
			MethodName: "SetBlockchainFee",
			Handler:    _Emulator_SetBlockchainFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x5b, 0x6b, 0xdb, 0x30,
	0x14, 0xc7, 0x49, 0x5d, 0x3a, 0xfb, 0xb4, 0x1b, 0x45, 0xbd, 0x24, 0xa8, 0x64, 0x0d, 0xde, 0x85,
	0xc2, 0x20, 0x0f, 0xdb, 0x1e, 0xf6, 0xba, 0x76, 0x17, 0x0a, 0x81, 0x0c, 0x87, 0x3d, 0xed, 0x21,
	0x73, 0xad, 0x33, 0x2a, 0xe6, 0x48, 0x99, 0x24, 0x17, 0xf2, 0x25, 0xf6, 0x99, 0x87, 0x64, 0x39,
	0x58, 0x71, 0xb2, 0xbe, 0xe5, 0xdc, 0x7e, 0x7f, 0xfb, 0x9c, 0x7f, 0x0c, 0x89, 0x5a, 0x16, 0xe3,
	0xa5, 0x92, 0x46, 0x92, 0x04, 0x17, 0x55, 0x99, 0x1b, 0x2e, 0x45, 0xfa, 0x13, 0xc8, 0x0c, 0x05,
	0xfb, 0x96, 0xaf, 0x16, 0x28, 0x4c, 0x86, 0x7f, 0x2a, 0xd4, 0x86, 0x9c, 0xc3, 0x81, 0x46, 0xc1,
	0x50, 0x0d, 0x7a, 0xa3, 0xde, 0x55, 0x92, 0xf9, 0x88, 0x50, 0x88, 0x15, 0x16, 0xc8, 0x1f, 0x50,
	0x0d, 0xf6, 0x5c, 0x65, 0x1d, 0xdb, 0x99, 0x7c, 0x21, 0x2b, 0x61, 0x06, 0xfb, 0xa3, 0xde, 0x55,
	0x94, 0xf9, 0x28, 0x3d, 0x83, 0x93, 0x40, 0x41, 0x2f, 0xa5, 0xd0, 0x98, 0xce, 0x80, 0x4c, 0x97,
	0x28, 0x6e, 0xee, 0x73, 0x21, 0xb0, 0x6c, 0x84, 0xfb, 0xf0, 0xa4, 0xd2, 0xa8, 0xe6, 0x9c, 0x35,
	0xca, 0x36, 0xbc, 0x65, 0xe4, 0x25, 0x3c, 0x2b, 0x65, 0xf1, 0x1b, 0xd9, 0xfc, 0x6e, 0x35, 0xb7,
	0x39, 0xa7, 0x1f, 0x65, 0x47, 0x75, 0xf6, 0x7a, 0xf5, 0x5d, 0xa3, 0x4a, 0xdf, 0xc3, 0x49, 0x00,
	0xad, 0xb5, 0xc8, 0x10, 0xa0, 0xa8, 0x53, 0x16, 0x1c, 0x39, 0x70, 0xe2, 0x33, 0xb7, 0xcc, 0x4e,
	0xdd, 0x94, 0x52, 0xe3, 0xc6, 0xb3, 0x3c, 0x32, 0x75, 0x0e, 0xa7, 0xe1, 0x94, 0x7f, 0xb1, 0x0f,
	0x40, 0x67, 0x68, 0xae, 0xed, 0x73, 0x7d, 0x45, 0xf1, 0xa9, 0x52, 0x6e, 0xd1, 0x0d, 0x94, 0x42,
	0xcc, 0x7c, 0xca, 0x21, 0xa3, 0x6c, 0x1d, 0xa7, 0x43, 0xb8, 0xd8, 0x3a, 0xe9, 0xc1, 0x6f, 0xa0,
	0xdf, 0x94, 0x8b, 0xfb, 0x9c, 0x8b, 0x2f, 0x88, 0x0d, 0xf5, 0x18, 0xa2, 0x5f, 0x88, 0x1e, 0x68,
	0x7f, 0xa6, 0x14, 0x06, 0xdd, 0x66, 0x0f, 0x9a, 0xc0, 0xe9, 0x0c, 0x8d, 0x5d, 0xd8, 0xc7, 0xc2,
	0xf0, 0x87, 0x35, 0xe5, 0x02, 0x12, 0xae, 0xe7, 0x52, 0x94, 0x5c, 0xa0, 0x5b, 0x7f, 0x9c, 0xc5,
	0x5c, 0x4f, 0x5d, 0xdc, 0xbe, 0xcc, 0x5e, 0xfb, 0x32, 0x69, 0x1f, 0xce, 0x36, 0x68, 0xb5, 0xcc,
	0xdb, 0xbf, 0xfb, 0x10, 0x7f, 0x76, 0x46, 0x93, 0x8a, 0x4c, 0xe0, 0xb0, 0xe5, 0x02, 0x32, 0x1c,
	0xaf, 0x2d, 0x38, 0xee, 0xfa, 0x8f, 0x3e, 0xdf, 0x55, 0xf6, 0x07, 0x9d, 0xc0, 0x61, 0xeb, 0xce,
	0x01, 0xad, 0x6b, 0xaa, 0x80, 0xb6, 0xcd, 0x1e, 0x53, 0x38, 0x6a, 0x5f, 0x92, 0xb4, 0xfb, 0xb7,
	0x18, 0x83, 0x5e, 0xee, 0xac, 0x7b, 0x60, 0x06, 0x4f, 0x83, 0x95, 0x90, 0xcb, 0xe0, 0x7d, 0xba,
	0xab, 0xa7, 0xa3, 0xdd, 0x0d, 0x9e, 0xc9, 0xec, 0xdf, 0xa8, 0x63, 0x0e, 0xf2, 0x2a, 0x1c, 0xdc,
	0x61, 0x3b, 0xfa, 0xfa, 0xb1, 0x36, 0xaf, 0xf2, 0x03, 0x8e, 0x37, 0x6d, 0x43, 0xd2, 0x2d, 0xb3,
	0x1b, 0x06, 0xa4, 0x2f, 0xfe, 0xdb, 0x53, 0xc3, 0xef, 0x0e, 0xdc, 0xd7, 0xe7, 0xdd, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x41, 0x23, 0x8d, 0xfc, 0x8a, 0x04, 0x00, 0x00,
}
